name: goldsense2
region: nyc

services:
  - name: web
    github:
      repo: shadowsilence94/goldSense
      branch: main
      deploy_on_push: true
    
    # Explicitly set the run command
    run_command: gunicorn --bind 0.0.0.0:$PORT app:app --workers 2 --timeout 120 --log-level info --access-logfile - --error-logfile -
    
    # Build settings
    build_command: pip install -r requirements.txt
    
    # Environment settings
    environment_slug: python
    
    # Resource settings
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Port configuration
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Routes
    routes:
      - path: /
